### ISSUE TITLE
Jupyter notebook doesn't open throughout the terminal (Mac)

### ISSUE THREAD

**Issue by agnesfe777** [inwe-boku/lecture-scientific-programming#13]
When I put in jupyter notebook in terminal it tells me that the command is not found. The strange thing is though that I can find Jupyter on my Mac installed in the library. I found many answers about that issue for example that I have to change the path of the file. But I have no idea where to find path files and which one to use. Another answer is to reinstall Anaconda again. But I'm not sure if I can reinstall it completely until the lesson starts; the process last week was kinda confusing for me... 😅 Therefore I don't have the homework right now... is it okay if I add it as soon as I solved those issues?

**Comment by lumbric** [comment]
Conda provides something called "environments", you can imagine it like a virtual computer inside your computer, something like a separated sandbox where software can be installed. Jupyter is probably installed in the default environment called "base". In order to use software or libraries installed in an environment, it has to be activated:
Try to run:

`conda activate base`

And then `jupyter notebook`.

**Comment by agnesfe777** [comment]
Now it tells me conda: command not found.
The thing is, after we installed anaconda I had to reinstall git on the following day because I wasn't able to commit in my terminal and after that me and my helper made some other changes. Maybe Anaconda was deleted aswell during this process or overwritten..?

**Comment by agnesfe777** [comment]
well it wasn't deleted.. sorry for that. Because its in the same folder that it was when we downloaded it and made some updates of Conda.

**Comment by agnesfe777** [comment]
so sorry for that... 😓 Vibol told me about the anaconda navigator and now the Conda activate base worked 😅👌

**Comment by lumbric** [comment]
Ah yes! Great, thanks @sanvibol!
