### ISSUE TITLE
Exercise 2 hw 05 AuthenticationException

### ISSUE THREAD

**Issue by adob360** [inwe-boku/lecture-scientific-programming#18]
![image](https://user-images.githubusercontent.com/62031671/81466750-3a929280-91d4-11ea-8814-69463ccec1ac.png)

This occured when I tried to do exercise two of homework 05. 
Password and username are definitely right, I copy pasted them while login to the Entso-e transparency platform. 

Earlier it said that I have to enable HostKey, but this vanished after executing it a second time. Do you have any idea what I am doing wrong?

**Comment by joph** [comment]
Really hard to tell from what I see. Did you change any of the code? Did you try creating another account and enter different credentials? Is your internet connection stable?

**Comment by adob360** [comment]
Thank you for the quick answer. I tried it again a couple of times and restarted my computer and it worked somehow.

**Comment by adob360** [comment]
One of my teammembers had the same problem and I think this issue occurs because of the registration process on entso-e. It takes some time untill you can use your new account fully (about an hour). In both our cases, the files downloaded but a warning occured: failed to load host keys. Since it downloaded the files I think this it's no problem. So if anyone has the same problem just wait and execute the cells after one hour.

**Comment by lumbric** [comment]
Hm that's weird. I just registered and it works for me. But download is
pretty slow. Maybe there is some issue on the server side. You can check if
you entered user/password correctly by printing the variables. But don't
forget to remove these cells before committing the file in Git, otherwise
you'll publish your user/password. Anyway, if it works now, let's assume
everything is fine! :)

>
