### ISSUE TITLE
HW 05: ModuleNotFoundError: No module named 'pysftp'

### ISSUE THREAD

**Issue by dodolinchen** [inwe-boku/lecture-scientific-programming#19]
My jupyter notebook gives me following error:

![Unbenanntw](https://user-images.githubusercontent.com/62103409/81904654-d7ce3c00-95c3-11ea-8039-bcc11cf39589.JPG)

I also checked >conda list and it showed me, that pysftp is installed.

(Sorry for the late issue, I didn't find time for it earlier this week.)

**Comment by lumbric** [comment]
The screenshot shows that you didn't run the cells in order (from top to
bottom). It doesn't fully explain what is going on, because conda says that
the package is already installed, but anyway can you rerun all cells from
the very top?

>

**Comment by joph** [comment]
Another issue may be that you have to run the jupyter notebook from the same conda environment as the notebook uses. So if you run the jupyter notebook command (in git bash) from the base environment, you also have to use the base environment for the notebook.

**Comment by dodolinchen** [comment]
> The screenshot shows that you didn't run the cells in order (from top to bottom). It doesn't fully explain what is going on, because conda says that the package is already installed, but anyway can you rerun all cells from the very top?
> […](#)

I did that straight after (was not the first time I restarted the notebook and it never worked)

> Another issue may be that you have to run the jupyter notebook from the same conda environment as the notebook uses. So if you run the jupyter notebook command (in git bash) from the base environment, you also have to use the base environment for the notebook.

I have started the conda "scientific-computing" environment in git-bash prior to running jupyter notebook and installing pysftp - apart from that, how could I check if my jupyter notebook is runnning in the conda environment or in the base environment now?

**Comment by dodolinchen** [comment]
![Unbenanntw1](https://user-images.githubusercontent.com/62103409/81907516-2da4e300-95c8-11ea-96dd-0efb8fd83269.JPG)

**Comment by dodolinchen** [comment]
![Unbenanntw3](https://user-images.githubusercontent.com/62103409/81907683-6cd33400-95c8-11ea-8efb-fcd7a6f4827f.JPG)

If I run **!conda list** it is installed, if I run **conda list** it is not shown to be installed?

**Comment by joph** [comment]
Try to run jupyter notebook from base.

**Comment by dodolinchen** [comment]
I removed the "!" from the first line **conda install....** and now it seems to work.
What does the "!" do exactly?

**Comment by joph** [comment]
Well spotted! !conda install runs a shell command (as if you would execute it in git bash). conda install apparantly (I didn't know this works) installs the package to the notebook environment.

**Comment by joph** [comment]
But I think Peter can clarify better than I can.

**Comment by lumbric** [comment]
I have no idea what is happening, this doesn't make sense at all to me :)

**Comment by dodolinchen** [comment]
well, as long as it works now I guess...
Thanks for the clarification Johannes - and sorry for confusing you Peter ;)

**Comment by lumbric** [comment]
I found a first hint:
- Normally shell commands (not Python, but on the OS terminal) have the [prefixed by an exclamation mark](https://ipython.readthedocs.io/en/stable/interactive/python-ipython-diff.html#shell-assignment). It's actually worth to read the documentation. You can do crazy shit and combine OS commands an Python, even in loops (haven't seen anyone doing this until now, though).
- Some commands can be run even without the `!` using a feature called [automagic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-automagic). This is often done for `cd`, but apparently it works also for conda.

But I couldn't find any reason why automagic should behave in a different way then the normal shell commands.

Note: none of this works in pure Python, only in Jupyter Notebooks ans IPython.

**Comment by lumbric** [comment]
Ah I think I have a theory!
@doris-wimmer just out of curiosity could you run `conda env list` and `!conda env list` in the notebook which you started from the scientific-computing environment?

Unfortunately working with [Jupyter notebooks and conda environments](https://stackoverflow.com/questions/58068818/how-to-use-jupyter-notebooks-in-a-conda-environment/58068850#58068850) has many pitfalls. I assume that Jupyter has been started from the scientific-computing environment, but because the executable `jupyter-notebook` is missing (package jupyter not installed in this environment) it falls back to the base environment somehow. Executing with ! will run in scientific-computing on the shell and install packages there, but Python actually runs from base, so you won't be able to use those packages. On the other hand when you run `conda` without the `!` the command is executed from the kernel, which lives in the base environment. And then you actually install and run everything in the base environment. Kind of makes sense, but probably should be fixed somehow in Jupyter... :-/

Anyway, if it works now, you are fine for the lecture in any case and this is now just to satisfy our curiosity.

**Comment by dodolinchen** [comment]
![Unbenanntw4](https://user-images.githubusercontent.com/62103409/81922760-dcebb500-95dc-11ea-9383-8f71409d9d98.JPG)

 Both times the same - does that confuse you now more or less?

**Comment by lumbric** [comment]
That confuses definitely more. Let's give up on that one, pretend nothing happened and be happy that it works now!
