### ISSUE TITLE
Today‘s lecture

### ISSUE THREAD

**Issue by annar85** [inwe-boku/lecture-scientific-programming#3]
Hello!
Because of private matters, I could not attend the lecture today. I read the introduction slides. What about the next lectures till april (because of the Corona Virus)?
Thank you!

**Comment by lumbric** [comment]
The lectures will be live streamed using http://learn.boku.ac.at/. There is a chat and you can even participate using your microphone or webcam. Please join the live stream at normal times and be prepared to answer questions regarding the homework or do exercises during the class!

The lecture/exercises are not prepared for this and we are not sure how well the streaming will work. So please be patient in case of troubles and otherwise participate actively in the chat!

**Comment by annar85** [comment]
Thanks a lot
